import Head from 'next/head'
import Image from 'next/image'
import { ApolloClient, createHttpLink, InMemoryCache, gql } from "@apollo/client";
import { setContext } from '@apollo/client/link/context';
// import styles from '../styles/Home.module.css'

export default function Home({ pinnedItems }) {
  return (
    <div className="text-centert bg-slate-400 justify-center text-center" >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="">
        <h1 className="">
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className="">
          Get started by editing{' '}
          <code className="">pages/index.js</code>
        </p>

        <div className="bg-blue-300 ml-3 flex items-center justify-center">
          {pinnedItems.map(item => {
            return (

              <a key={item.id} href={item.url} className="bg-blue-400 block h-20 m-3  w-96 ">
                <h2  className='mt-4'>{ item.name }</h2>
                <p className='mt-4'> ⭐ {item.stargazers.totalCount }</p>
                <p  className='mt-4'>🍴 {item.forks.totalCount }</p>
  
                 <p  className='mt-4'>{item.primaryLanguage.name}</p>
                <p  className='mt-4 bg-[`${#3178c6}`]'>{item.primaryLanguage.color}</p>
              </a>
            )
          })}
        </div>
      </main>

      <footer className="">
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className="">
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export async function getStaticProps() {
  const httpLink = createHttpLink({
    uri: 'https://api.github.com/graphql',
  });

  const authLink = setContext((_, { headers }) => {
    return {
      headers: {
        ...headers,
        authorization: `Bearer ${process.env.GITHUB_ACCESS_TOKEN}`,
      }
    }
  });

  const client = new ApolloClient({
    link: authLink.concat(httpLink),
    cache: new InMemoryCache()
  });

  const { data } = await client.query({
    query: gql`
      {
        user(login: "kyoichi1") {
          pinnedItems(first: 6, types: [REPOSITORY]) {
            totalCount
            edges {
              node {
                ... on Repository {
                  name
                  id
                  url
                  primaryLanguage {
                    id
                    color
                    name
                  }
                  stargazers {
                    totalCount
                  }
                  forks {
                    totalCount
                  }
                }
              }
            }
          }
        }
      }
    `
  });

  const { user } = data;
  const pinnedItems = user.pinnedItems.edges.map(edge => edge.node);

  return {
    props: {
      pinnedItems
    }
  }
}